# Generated by Django 3.1 on 2020-09-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=20)),
                ('Make', models.CharField(max_length=20)),
                ('Year', models.CharField(max_length=4)),
                ('Views_Per_Day', models.FloatField()),
                ('Views_Per_Day_1', models.FloatField()),
                ('Views_Per_Day_2', models.FloatField()),
                ('Views_Per_Day_3', models.FloatField()),
                ('Views_Per_Day_4', models.FloatField()),
                ('Views', models.IntegerField()),
                ('DaysOnline', models.FloatField()),
            ],
            options={
                'db_table': 'Car',
                'managed': False,
            },
        ),
    ]
